<a href="https://colab.research.google.com/github/ezahner/IDS/blob/main/Extra%20Credit/alcohol_consumption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Erin Zahner

### **Alcohol Consumption and Deaths**

* Letâ€™s use a dataset of the number of deaths from excessive wine consumption.

* The dataset consists of the following attributes:

![image.png]()

In [179]:
# used for data analysis in Python

import pandas as pd

In [180]:
# Pandas read_csv from url

url = "https://raw.githubusercontent.com/bforoura/IDS/main/alcohol_deaths.csv"

df = pd.read_csv(url, sep=",")

In [181]:
# display info about the df attributes and their types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  21 non-null     object
 1   Alcohol  21 non-null     float64
 2   Deaths   21 non-null     int64
 3   Heart    19 non-null     float64
 4   Liver    20 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 968.0+ bytes

In [182]:
# display the entire data frame

df

           Country  Alcohol  Deaths  Heart      Liver
0        Australia     2.50     785  211.0  15.300000
1          Austria     3.00     863  167.0  45.599998
2   Belg. and Lux.     2.90     883  131.0  20.700001
3           Canada     2.40     793    NaN  16.400000
4          Denmark     2.90     971  220.0  23.900000
5          Finland     0.80     970  297.0  19.000000
6           France     9.10     751   11.0  37.900002
7          Iceland    -0.80     743  211.0  11.200000
8          Ireland     0.70    1000  300.0   6.500000
9           Israel     0.60    -834  183.0  13.700000
10           Italy    27.90     775  107.0  42.200001
11           Japan     1.50     680   36.0  23.200001
12     Netherlands     1.80     773  167.0   9.200000
13     New Zealand     1.90     916  266.0   7.700000
14          Norway     0.08     806  227.0  12.200000
15           Spain     6.50     724    NaN        NaN
16          Sweden     1.60     743  207.0  11.200000
17     Switzerland     5.80     693  115.0  20.299999
18              UK     1.30     941  285.0  10.300000
19              US     1.20     926  199.0  22.100000
20    West Germany     2.70     861  172.0  36.700001

In [183]:
# print size of columns and rows in the data frame

df.shape

(21, 5)

In [184]:
# display a column using associative addressing

df['Country']

0          Australia
1            Austria
2     Belg. and Lux.
3             Canada
4            Denmark
5            Finland
6             France
7            Iceland
8            Ireland
9             Israel
10             Italy
11             Japan
12       Netherlands
13       New Zealand
14            Norway
15             Spain
16            Sweden
17       Switzerland
18                UK
19                US
20      West Germany
Name: Country, dtype: object

In [185]:
# display distinct count of row values (frequencies)

df['Country'].value_counts()

Australia         1
Japan             1
US                1
UK                1
Switzerland       1
Sweden            1
Spain             1
Norway            1
New Zealand       1
Netherlands       1
Italy             1
Austria           1
Israel            1
Ireland           1
Iceland           1
France            1
Finland           1
Denmark           1
Canada            1
Belg. and Lux.    1
West Germany      1
Name: Country, dtype: int64

In [186]:
# select the column with index position 0

df.iloc[:, 0]

0          Australia
1            Austria
2     Belg. and Lux.
3             Canada
4            Denmark
5            Finland
6             France
7            Iceland
8            Ireland
9             Israel
10             Italy
11             Japan
12       Netherlands
13       New Zealand
14            Norway
15             Spain
16            Sweden
17       Switzerland
18                UK
19                US
20      West Germany
Name: Country, dtype: object

In [187]:
# select columns with index positions 1 and 2

df.iloc[:, [1, 2]]

    Alcohol  Deaths
0      2.50     785
1      3.00     863
2      2.90     883
3      2.40     793
4      2.90     971
5      0.80     970
6      9.10     751
7     -0.80     743
8      0.70    1000
9      0.60    -834
10    27.90     775
11     1.50     680
12     1.80     773
13     1.90     916
14     0.08     806
15     6.50     724
16     1.60     743
17     5.80     693
18     1.30     941
19     1.20     926
20     2.70     861

In [188]:
# select columns with index positions as a range

df.iloc[:, 1:3]

    Alcohol  Deaths
0      2.50     785
1      3.00     863
2      2.90     883
3      2.40     793
4      2.90     971
5      0.80     970
6      9.10     751
7     -0.80     743
8      0.70    1000
9      0.60    -834
10    27.90     775
11     1.50     680
12     1.80     773
13     1.90     916
14     0.08     806
15     6.50     724
16     1.60     743
17     5.80     693
18     1.30     941
19     1.20     926
20     2.70     861

In [189]:
# select a single cell

df.iloc[0,0]

'Australia'

In [190]:
# select specific columns and rows with index positions as lists

df.iloc[[1,3,4], [2,3]]

   Deaths  Heart
1     863  167.0
3     793    NaN
4     971  220.0

In [191]:
# select all columns and rows

df.iloc[:, :]

           Country  Alcohol  Deaths  Heart      Liver
0        Australia     2.50     785  211.0  15.300000
1          Austria     3.00     863  167.0  45.599998
2   Belg. and Lux.     2.90     883  131.0  20.700001
3           Canada     2.40     793    NaN  16.400000
4          Denmark     2.90     971  220.0  23.900000
5          Finland     0.80     970  297.0  19.000000
6           France     9.10     751   11.0  37.900002
7          Iceland    -0.80     743  211.0  11.200000
8          Ireland     0.70    1000  300.0   6.500000
9           Israel     0.60    -834  183.0  13.700000
10           Italy    27.90     775  107.0  42.200001
11           Japan     1.50     680   36.0  23.200001
12     Netherlands     1.80     773  167.0   9.200000
13     New Zealand     1.90     916  266.0   7.700000
14          Norway     0.08     806  227.0  12.200000
15           Spain     6.50     724    NaN        NaN
16          Sweden     1.60     743  207.0  11.200000
17     Switzerland     5.80     693  115.0  20.299999
18              UK     1.30     941  285.0  10.300000
19              US     1.20     926  199.0  22.100000
20    West Germany     2.70     861  172.0  36.700001

In [192]:
# find the min, max, mean and std of the Heart column

min = df['Heart'].min()
max = df['Heart'].max()
mean = df['Heart'].mean()
std = df['Heart'].std()

print("Min, Max, Mean, Std : ", min, max, mean, std)
print('--------------------------------------------')
print(f"Min: {min}, Max: {max}, Mean: {mean}, Std: {std}")

Min, Max, Mean, Std :  11.0 300.0 184.8421052631579 79.77347314454761
--------------------------------------------
Min: 11.0, Max: 300.0, Mean: 184.8421052631579, Std: 79.77347314454761

In [193]:
# noramlize the Heart column using z-scoring

(df['Heart']- mean) / std

0     0.327902
1    -0.223660
2    -0.674937
3          NaN
4     0.440722
5     1.405955
6    -2.179197
7     0.327902
8     1.443561
9    -0.023092
10   -0.975789
11   -1.865810
12   -0.223660
13    1.017354
14    0.528470
15         NaN
16    0.277760
17   -0.875505
18    1.255529
19    0.177476
20   -0.160982
Name: Heart, dtype: float64

In [194]:
# noramlize the Heart column using minmax scaling

(df['Heart']- min) / (max - min)

0     0.692042
1     0.539792
2     0.415225
3          NaN
4     0.723183
5     0.989619
6     0.000000
7     0.692042
8     1.000000
9     0.595156
10    0.332180
11    0.086505
12    0.539792
13    0.882353
14    0.747405
15         NaN
16    0.678201
17    0.359862
18    0.948097
19    0.650519
20    0.557093
Name: Heart, dtype: float64

In [195]:
# are there any non-number (missing) values in this column?

df['Heart'].isna()

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
20    False
Name: Heart, dtype: bool

In [196]:
# Fill NaN Values in the Heart Column with the Mean value (impute)

df['Heart'] = df['Heart'].fillna(df['Heart'].mean())

In [197]:
# Remove negative values for Alcohol

df['Alcohol'] = df['Alcohol'].abs()

In [198]:
# Data reduction for Heart

df['Heart'].round(decimals = 1)

0     211.0
1     167.0
2     131.0
3     184.8
4     220.0
5     297.0
6      11.0
7     211.0
8     300.0
9     183.0
10    107.0
11     36.0
12    167.0
13    266.0
14    227.0
15    184.8
16    207.0
17    115.0
18    285.0
19    199.0
20    172.0
Name: Heart, dtype: float64

In [199]:
# examine the partially cleansed data

df

           Country  Alcohol  Deaths       Heart      Liver
0        Australia     2.50     785  211.000000  15.300000
1          Austria     3.00     863  167.000000  45.599998
2   Belg. and Lux.     2.90     883  131.000000  20.700001
3           Canada     2.40     793  184.842105  16.400000
4          Denmark     2.90     971  220.000000  23.900000
5          Finland     0.80     970  297.000000  19.000000
6           France     9.10     751   11.000000  37.900002
7          Iceland     0.80     743  211.000000  11.200000
8          Ireland     0.70    1000  300.000000   6.500000
9           Israel     0.60    -834  183.000000  13.700000
10           Italy    27.90     775  107.000000  42.200001
11           Japan     1.50     680   36.000000  23.200001
12     Netherlands     1.80     773  167.000000   9.200000
13     New Zealand     1.90     916  266.000000   7.700000
14          Norway     0.08     806  227.000000  12.200000
15           Spain     6.50     724  184.842105        NaN
16          Sweden     1.60     743  207.000000  11.200000
17     Switzerland     5.80     693  115.000000  20.299999
18              UK     1.30     941  285.000000  10.300000
19              US     1.20     926  199.000000  22.100000
20    West Germany     2.70     861  172.000000  36.700001

In [200]:
# Let's add the wrangled data for India

df = df.append({'Country': 'India', 'Alcohol':2.53, 'Deaths': 'NA', 'Heart': 171, 'Liver': 'NA'}, ignore_index=True)

<ipython-input-200-66ebeb90ba5c>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'Country': 'India', 'Alcohol':2.53, 'Deaths': 'NA', 'Heart': 171, 'Liver': 'NA'}, ignore_index=True)

In [201]:

"""  Discretize Alcohol

o	0: less than or equal to 1.00 per capita
o	1: more than 1.00 but less than or equal to 2.00 per capita
o	2: more than 2.00 but less than or equal to 5.00 per capita
o	3: more than 5.00 per capita

"""

df['Alcohol'] = pd.cut(x=df['Alcohol'], bins=[0, 1, 2, 5, 100], labels = [0, 1, 2, 3])

df

           Country Alcohol Deaths       Heart      Liver
0        Australia       2    785  211.000000       15.3
1          Austria       2    863  167.000000  45.599998
2   Belg. and Lux.       2    883  131.000000  20.700001
3           Canada       2    793  184.842105       16.4
4          Denmark       2    971  220.000000       23.9
5          Finland       0    970  297.000000       19.0
6           France       3    751   11.000000  37.900002
7          Iceland       0    743  211.000000       11.2
8          Ireland       0   1000  300.000000        6.5
9           Israel       0   -834  183.000000       13.7
10           Italy       3    775  107.000000  42.200001
11           Japan       1    680   36.000000  23.200001
12     Netherlands       1    773  167.000000        9.2
13     New Zealand       1    916  266.000000        7.7
14          Norway       0    806  227.000000       12.2
15           Spain       3    724  184.842105        NaN
16          Sweden       1    743  207.000000       11.2
17     Switzerland       3    693  115.000000  20.299999
18              UK       1    941  285.000000       10.3
19              US       1    926  199.000000       22.1
20    West Germany       2    861  172.000000  36.700001
21           India       2     NA  171.000000         NA

In [202]:
#Change "NA" to NaN
df['Deaths'] = pd.to_numeric(df['Deaths'], errors='coerce')

In [203]:
#Fill in NaN with mean of column
df['Deaths'] = df['Deaths'].fillna(df['Deaths'].mean())

In [204]:
#Change all negative numbers to positive
df['Deaths'] = df['Deaths'].abs()

In [205]:
#Change "NA" to NaN
df['Liver'] = pd.to_numeric(df['Liver'], errors='coerce')

In [206]:
#Fill in NaN with mean of column
df['Liver'] = df['Liver'].fillna(df['Liver'].mean())

In [207]:
"""
  Discretize Deaths:
o	6: greater than or equal to 600 but less than 700 per captita
o	7: greater than or equal to 700 but less than 800 per captita
o	8: greater than or equal to 800 but less than 900 per captita
o	9: greater than or equal to 900 but less than 1000 per captita
o 10: greater than or equal to 1000 per capita


"""

df['Deaths'] = pd.cut(x=df['Deaths'], bins=[600, 700, 800, 900, 1000, 100000], labels = [6, 7, 8, 9, 10])
df

           Country Alcohol Deaths       Heart      Liver
0        Australia       2      7  211.000000  15.300000
1          Austria       2      8  167.000000  45.599998
2   Belg. and Lux.       2      8  131.000000  20.700001
3           Canada       2      7  184.842105  16.400000
4          Denmark       2      9  220.000000  23.900000
5          Finland       0      9  297.000000  19.000000
6           France       3      7   11.000000  37.900002
7          Iceland       0      7  211.000000  11.200000
8          Ireland       0      9  300.000000   6.500000
9           Israel       0      8  183.000000  13.700000
10           Italy       3      7  107.000000  42.200001
11           Japan       1      6   36.000000  23.200001
12     Netherlands       1      7  167.000000   9.200000
13     New Zealand       1      9  266.000000   7.700000
14          Norway       0      8  227.000000  12.200000
15           Spain       3      7  184.842105  20.265000
16          Sweden       1      7  207.000000  11.200000
17     Switzerland       3      6  115.000000  20.299999
18              UK       1      9  285.000000  10.300000
19              US       1      9  199.000000  22.100000
20    West Germany       2      8  172.000000  36.700001
21           India       2      7  171.000000  20.265000

In [208]:
#delete India row
df = df.drop(21)

In [209]:
#delete Alcohol column
del df['Alcohol']
df

           Country Deaths       Heart      Liver
0        Australia      7  211.000000  15.300000
1          Austria      8  167.000000  45.599998
2   Belg. and Lux.      8  131.000000  20.700001
3           Canada      7  184.842105  16.400000
4          Denmark      9  220.000000  23.900000
5          Finland      9  297.000000  19.000000
6           France      7   11.000000  37.900002
7          Iceland      7  211.000000  11.200000
8          Ireland      9  300.000000   6.500000
9           Israel      8  183.000000  13.700000
10           Italy      7  107.000000  42.200001
11           Japan      6   36.000000  23.200001
12     Netherlands      7  167.000000   9.200000
13     New Zealand      9  266.000000   7.700000
14          Norway      8  227.000000  12.200000
15           Spain      7  184.842105  20.265000
16          Sweden      7  207.000000  11.200000
17     Switzerland      6  115.000000  20.299999
18              UK      9  285.000000  10.300000
19              US      9  199.000000  22.100000
20    West Germany      8  172.000000  36.700001

In [212]:
df['Heart'] = df['Heart'].round(decimals = 1)
df['Liver'] = df['Liver'].round(decimals = 1)
df

           Country Deaths  Heart  Liver
0        Australia      7  211.0   15.3
1          Austria      8  167.0   45.6
2   Belg. and Lux.      8  131.0   20.7
3           Canada      7  184.8   16.4
4          Denmark      9  220.0   23.9
5          Finland      9  297.0   19.0
6           France      7   11.0   37.9
7          Iceland      7  211.0   11.2
8          Ireland      9  300.0    6.5
9           Israel      8  183.0   13.7
10           Italy      7  107.0   42.2
11           Japan      6   36.0   23.2
12     Netherlands      7  167.0    9.2
13     New Zealand      9  266.0    7.7
14          Norway      8  227.0   12.2
15           Spain      7  184.8   20.3
16          Sweden      7  207.0   11.2
17     Switzerland      6  115.0   20.3
18              UK      9  285.0   10.3
19              US      9  199.0   22.1
20    West Germany      8  172.0   36.7

### **Extra Credit**

1. Replace the negative numbers in **Alcohol** and **Deaths** with their absolute values
2. Impute all missing values using column means
3. Discretize **Deaths** using your own judgment
4. Display the modified dataframe
5. Delete the India row
6. Delete the Alcohol column
7. Reduce all numeric data to one decimal place
7. Display the modified dataframe